services:
  mqtt-server:
    container_name: power-control
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "80:80"
    environment:
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - .:/usr/src/app
