version: '3'

services:
  mqtt-server:
    container_name: power-control
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "80:80"
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: postgres
      PG_HOST: postgres
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - postgres

volumes:
  pg_data: